# Generated by Django 6.0.1 on 2026-01-16 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(default='SIT Pune', max_length=100)),
                ('branch', models.CharField(default='CSE', max_length=50)),
                ('current_year', models.IntegerField(default=1)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('target_cgpa', models.FloatField(default=9.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
