# Generated by Django 6.0.1 on 2026-01-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subject_attendancesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='lectures_attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
    ]
