# Generated by Django 6.0.1 on 2026-01-18 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ainote'),
    ]

    operations = [
        migrations.AddField(
            model_name='ainote',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject'),
        ),
    ]
