# Generated by Django 6.0.1 on 2026-01-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ainote_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_theory',
            field=models.BooleanField(default=True),
        ),
    ]
