# Generated by Django 6.0.1 on 2026-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_subject_is_theory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(default='Not Set', max_length=50),
        ),
    ]
